// swift-tools-version:5.9
// Generated by `flutter-watchos plugin port`. Do not edit by hand.
//
// FFI plugin manifest. The flutter-watchos CLI discovers the plugin through
// this file, compiles `Classes/*.m` into a static archive force-loaded into
// the watch binary, and links the frameworks declared below.
import PackageDescription

let package = Package(
    name: "in_app_purchase_watchos",
    platforms: [
        .watchOS("7.0"),
    ],
    products: [
        .library(name: "in-app-purchase-watchos", targets: ["in_app_purchase_watchos"]),
    ],
    targets: [
        .target(
            name: "in_app_purchase_watchos",
            path: "Classes",
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("."),
            ],
            linkerSettings: [
                .linkedFramework("Foundation"),
                // SKProductsRequest and friends.
                .linkedFramework("StoreKit"),
            ]
        ),
    ]
)
