name: firebase_messaging_example
description: "watchOS example for firebase_messaging_watchos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: any
  firebase_messaging_watchos:
    path: ../
  firebase_core: "^4.12.1"
  firebase_core_watchos:
    path: ../../firebase_core_watchos
  flutter_local_notifications: "^21.0.0"
  http: "^1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
